### ISSUE TITLE
Unable to import Require Export statements.

### ISSUE THREAD

**Issue by ianzen** [mkolosick/Sublime-Coq#10]
I am not able to import previously compiled files through Require Import. The .v, .vo, .aux and .glob files are all located in the same directory. Coqtop and Coqc both work with Require Import from the command line. CoqIDE, ProofGeneral both work as well. 

These are my settings for Sublime-Coq:

{
    "coqtop_path": "C:\\Coq\\bin\\coqtop.exe",
    "coqtop_args": [],
    // "coq_debug": ["coqtop", "manager"],
    "coq_debug": [],
}

**Comment by mkolosick** [comment]
This was never in a state where it actually worked on more than my computer. At this point I only maintain the syntax highlighting because GitHub uses it for their Coq syntax highlighting.

**Comment by ianzen** [comment]
Thanks for the heads up. That's quite unfortunate because the package looked quite promising.

**Comment by ianzen** [comment]
OK, I think I know the problem. Sublime-Coq isn't setting the -R flag to the pwd shown in sublime.
