### ISSUE TITLE
Hihglighting of multiline comments broken

### ISSUE THREAD

**Issue by pchaigno** [mkolosick/Sublime-Coq#4]
Keywords in the multiline comments are highlighted. See [this line](https://github.com/shouya/thinking-dumps/blob/master/imp/Chap7.v#L131) for instance. It has a `Qed` highlighted in a comment.

This issue was originaly reported by @shouya in github/linguist#1804.

**Comment by pchaigno** [comment]
@mkolosick Did you get a chance to look into this?

**Comment by mkolosick** [comment]
So the real issue here seems to be the nested multiline comment on https://github.com/shouya/thinking-dumps/blob/master/imp/Chap7.v#L130.

As syntax highlighting is done via regular expression I don't believe it is possible to handle this case.

Does this make sense or am I missing something?

**Comment by pchaigno** [comment]
Are nested comments allowed in Coq?

If they are, I think it can be implemented with regular expressions. For example Racket has nested comments:
```racket
#| a comment  #| still a comment |# even 
                                      more comment |#
```
You can find as a reference the grammar used to highlight Racket code on GitHub at [soegaard/racket-highlight-for-github](https://github.com/soegaard/racket-highlight-for-github).

**Comment by mkolosick** [comment]
I just pushed a change. Can you confirm that this fixed the issue then I'll close this?

**Comment by pchaigno** [comment]
Yep, [it look fixed](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fmkolosick%2FSublime-Coq%2Fmaster%2FCoq.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fshouya%2Fthinking-dumps%2Fmaster%2Fimp%2FChap7.v&code=). Thanks! :zap:

**Comment by mkolosick** [comment]
@pchaigno will you handle getting GitHub to use the new version for linguist?

**Comment by pchaigno** [comment]
I won't personally, but it will be updated with the next version of Linguist ;)

**Comment by mkolosick** [comment]
Ah. Wasn't sure how linguist worked
