### ISSUE TITLE
Syntax highlighting broken after a Defined

### ISSUE THREAD

**Issue by Zimmi48** [mkolosick/Sublime-Coq#5]
Hi,

I have not tested this plugin but Github uses it for its syntax highlighting of Coq code and it appears that syntax highlighting breaks when a proof is ended with `Defined`.
See here for instance: https://github.com/pedagand/cortouche/blob/5e71d0ff65c2c4ca9ad255dff1c336aba5dc3459/test-suite/demo.v

Thanks!

**Comment by mkolosick** [comment]
I believe commit `ea50572` fixes this.

**Comment by Zimmi48** [comment]
Perfect!
