### ISSUE TITLE
Notation with recursive patterns is separately passed

### ISSUE THREAD

**Issue by ch96an** [mkolosick/Sublime-Coq#7]
`Notation "[ x ; .. ; y ]" := (cons x .. (cons y nil) ..).
`
this code is separated by regular expression '(.|\n)*?\.( |\n|$)'
so only
`Notation "[ x ; .. 
`
is passed to coqtop

**Comment by mkolosick** [comment]
Hi this plugin was never really fully functional. I personally use ProofGeneral in Emacs now. So feel free to fork and fix this, but I am unlikely to update it.
