### ISSUE TITLE
Is this code still licensed under an MIT license?

### ISSUE THREAD

**Issue by lildude** [mkolosick/Sublime-Coq#9]
👋  from GitHub's Linguist team.

I noticed you've stripped this repo down to the bare minimum in https://github.com/mkolosick/Sublime-Coq/commit/1040068949c904dd347c360669b9943ab181f114 and at the same time removed the LICENSE file.

We use this to confirm we have the necessary permissions to include the repository with Linguist and as such I need to know if this repo is still licensed under the MIT license.

If so, would you mind re-instating the LICENSE file so we can continue to automate this validation? Alternatively, if you know of another grammar for this language, please let me know and we'll happily switch grammars.

Thanks 🙇‍♂️

**Comment by mkolosick** [comment]
Hi I've restored the LICENSE file in 0d1f70727b19007e55780bcd7b74f70c399eba3b
